# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ba93e2b2cd57db01ba46673d35fbcddc2db52a12153fa7503e2362fbe5dc650dd5c46975afce2b7027d60ee285ed5e2cc89c958f63ad0ed8a9301e5ce236464

test:
  secret_key_base: eabeb8d8abf48e0618bd877964418157467d6f1e7666b336f484b3cc8d4348ba529f3b8a57675c3ea23d188f7e0c3af75a30f88593dbbcae20fd47627456db96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
